---
# tasks file for lvm

- include: prereq.yml

- name: ansible-volumes | loop over vgs
  include_tasks: vg.yml
  loop: "{{ lvm_groups }}"
  loop_control:
    loop_var: avvg
  when: >
    manage_lvm is defined and
    manage_lvm

- include: autoextends.yml
  loop: "{{ lvm_groups }}"
  loop_control:
    loop_var: avvg
  when: >
    manage_lvm is defined and
    manage_lvm
