---
dependency:
  name: galaxy
  options:
    role-file: requirements.yml
    roles-path: ../community
driver:
  name: vagrant
  provider:
    name: virtualbox

lint: yamllint . && flake8 && ansible-lint --exclude=meta
platforms:
  - name: Fedora-Molecule-Virtualization
    box: fedora/33-cloud-base
    provider_options:
      cpus: 4
      memory: 8092
    instance_raw_config_args:
      - "cache.enable :dnf"
      - "cache.auto_detect = false"
    provider_raw_config_args:
      - "customize ['modifyvm', :id, '--nested-hw-virt', 'on']"
      - "customize ['storagectl', :id, '--name', 'IDE', '--hostiocache', 'on']"
    provider_override_args:
      - "persistent_storage.enabled = true"
      - "persistent_storage.location = 'molecule-virtualization.vdi'"
      - "persistent_storage.size = 100"
      - "persistent_storage.mount = false"
      - "persistent_storage.diskdevice = '/dev/sdb'"
provisioner:
  name: ansible
  env:
    ANSIBLE_ROLES_PATH: ../../..:../../../community
verifier:
  name: testinfra
  env:
    PYTHONWARNINGS: "ignore:.*U.*mode is deprecated:DeprecationWarning"
  options:
    v: 1
