---

dist: focal

language: python
python:
  - "3.8"

addons:
  apt:
    sources:
      - sourceline: 'deb [arch=amd64] https://apt.releases.hashicorp.com $(lsb_release -cs) main'
        key_url: 'https://apt.releases.hashicorp.com/gpg'
    update: true
    packages:
      - bridge-utils
      - dnsmasq-base
      - ebtables
      - libvirt-bin
      - libvirt-dev
      - qemu-kvm
      - qemu-utils
      - ruby-dev
      - ca-certificates
      - curl
      - gcc
      - iproute2
      - sudo
      - vagrant

install:
  - vagrant plugin install vagrant-libvirt
  - pip install wheel pyopenssl tox
  - sudo chmod o+rwx /var/run/libvirt/libvirt-sock

script:
  - mv ../ansible-virtualization-guest ../tcharl.ansible_virtualization_guest
  - travis_wait 60 tox -e test-exec -- --scenario-name kvm
branches:
  only:
    - master
