---
roles:
  # Install a role from Ansible Galaxy.
  - name: tcharl.ansible_routing
    source: https://galaxy.ansible.com

  - name: mrlesmithjr.ansible-manage-lvm
    source: https://galaxy.ansible.com

  - name: tcharl.ansible_volumes
    source: https://galaxy.ansible.com

  - name: tcharl.ansible_users
    source: https://galaxy.ansible.com

  - name: tcharl.ansible_securehost
    source: https://galaxy.ansible.com

  - name: robertdebock.fail2ban
    source: https://galaxy.ansible.com

  - name: robertdebock.users
    source: https://galaxy.ansible.com

  - name: robertdebock.epel
    source: https://galaxy.ansible.com

  - name: robertdebock.bootstrap
    source: https://galaxy.ansible.com

  - name: robertdebock.core_dependencies
    source: https://galaxy.ansible.com

  - name: tcharl.ansible_virtualization
    source: https://galaxy.ansible.com

  - name: tcharl.ansible_role_libvirt_host
    source: https://galaxy.ansible.com

  - name: stackhpc.libvirt-vm
    source: https://galaxy.ansible.com

  - name: geerlingguy.ntp
    source: https://galaxy.ansible.com
