---
roles:
  # Install a role from Ansible Galaxy.

  - name: tcharl.ansible_virtualization
    source: https://galaxy.ansible.com
    path: ../community

  - name: stackhpc.libvirt-vm
    source: https://galaxy.ansible.com
    path: ../community
