---
- name: Converge
  hosts: all
  vars:
    manage_lvm: true
    lvm_groups:
      - vgname: non-persistent
        disks:
          - /dev/sdb1
        create: true
    libvirt_host_pools:
      - name: libvirt_vg
        type: lvm2
        source: non-persistent
    libvirt_host_networks:
      - name: default
        mode: nat
        bridge: virbr0
        ip: 192.168.122.1
        netmask: 255.255.255.0
        dhcp_start: 192.168.122.100
        dhcp_end: 192.168.122.200
    users_group_list2:
      - name: libvirt
    systemusers_user_list:
      - name: libvirt
        group: libvirt
        groups: wheel
    virtualization_guest_boxes:
      - name: fedoraKubeMasterVM
        url: https://download.fedoraproject.org/pub/fedora/linux/releases/33/Cloud/x86_64/images/Fedora-Cloud-Base-Vagrant-33-1.2.x86_64.vagrant-libvirt.box
        memory_mb: 2048
        vcpus: 1
        recreate_machine: False
        ssh_port_on_host: "6752" # same as the one in molecule.yml
        ansible_groups:
          - kube_master
        interfaces:
          - network: default
      - name: fedoraKubeNodeVM
        url: https://download.fedoraproject.org/pub/fedora/linux/releases/33/Cloud/x86_64/images/Fedora-Cloud-Base-Vagrant-33-1.2.x86_64.vagrant-libvirt.box
        memory_mb: 2048
        vcpus: 1
        recreate_machine: True
        ssh_port_on_host: "6753" # same as the one in molecule.yml
        ansible_groups:
          - kube_node
        interfaces:
          - network: default
  roles:
    - role: tcharl.ansible_virtualization_guest
  tasks:
    - name: ansible-virtualization-guest | handler | execute hook # firewalld overriding vm NAT
      ansible.builtin.service:
        name: libvirtd
        state: restarted
      become: true
