---
dependency:
  name: galaxy
  options:
    requirements-file: requirements-collections.yml
    collections-path: ../community-collections
    role-file: requirements.yml
    roles-path: ../community
driver:
  name: vagrant
  provider:
    name: virtualbox
lint: yamllint . && flake8 && ansible-lint --exclude=meta
platforms:
  - name: Fedora-Molecule-Virtualization-Guest-VB
    box: fedora/31-cloud-base
    provider_options:
      cpus: 8
      memory: 12288
    provider_raw_config_args:
      - "customize ['modifyvm', :id, '--nested-hw-virt', 'on']"
    instance_raw_config_args:
      - "vm.network :forwarded_port, guest: 6752, host: 6752, protocol: 'tcp'"
      - "vm.network :forwarded_port, guest: 6753, host: 6753, protocol: 'tcp'"
    provider_override_args:
      - "persistent_storage.enabled = true"
      - "persistent_storage.location = 'molecule-virtualization-guest.vdi'"
      - "persistent_storage.size = 7000"
      - "persistent_storage.mount = false"
      - "persistent_storage.diskdevice = '/dev/sdb'"

provisioner:
  name: ansible
  env:
    ANSIBLE_ROLES_PATH: ../../..:../../../community
verifier:
  name: testinfra
  env:
    PYTHONWARNINGS: "ignore:.*U.*mode is deprecated:DeprecationWarning"
  options:
    v: 1
