---
- name: Ansible-hosts | add vm to hosts (ansible_ssh_private_key_file should be defined)
  ansible.builtin.debug:
    msg: ansible_ssh_private_key_file
  register: ansible_ssh_private_key_file_vm

- name: Ansible-hosts | add vm to hosts
  ansible.builtin.add_host:
    name: "{{ clientid }}"
    ansible_port: "{{ sshport }}"
    ansible_user: "{{ whoami.stdout }}"
    ansible_ssh_private_key_file: "{{ ansible_ssh_private_key_file_vm.msg }}"
    ansible_ssh_extra_args: "-o StrictHostKeyChecking=no"
    groups:
     "{{ ['vms'] + (virtualmachine.ansible_groups | default(omit)) | list }}"
  changed_when: false

- name: Ansible-hosts | debug vm groups
  ansible.builtin.debug:
    msg: >
      The vm {{ clientid }} will be available
      at host {{ hostip }}
      and port {{ sshport }}
      and be added to the following ansible groups
      {{ ['vms'] + (virtualmachine.ansible_groups | default(omit)) | list }}
      Consider login with root and to change the insecure password
