---

- name: Delete-vm-network-host | get current network xml
  community.libvirt.virt_net:
    command: get_xml
    name: "{{ nic.network }}"
  register: network_xml
  become: True

- name: Delete-vm-network-host | extract current network xml
  community.general.xml:
    xmlstring: "{{ network_xml.get_xml }}"
    xpath: "/network/ip/dhcp/host[@name='{{ virtualmachine.name }}']"  # /mac/@address
    content: attribute
  failed_when: false
  register: already_registered_hosts

- name: Delete-vm-network-host | debug current network xml
  ansible.builtin.debug:
    var: already_registered_hosts
    verbosity: 2

- name: Delete-vm-network-host | remove dhcp host configuration
  ansible.builtin.command: "virsh net-update {{ nic.network }} delete ip-dhcp-host \"<host mac='{{ already_registered_hosts.matches.0.host.mac }}' name='{{ already_registered_hosts.matches.0.host.name }}' ip='{{ already_registered_hosts.matches.0.host.ip }}'/>\""
  changed_when: false
  failed_when: false
  when:
    - not already_registered_hosts is failed
    - already_registered_hosts.count is defined
    - already_registered_hosts.count > 0
  become: true
