---

- name: ansible-virtualization-guest | delete-vm | get the network facts
  community.libvirt.virt_net:
    command: facts
  register: virsh_net_facts

- name: ansible-virtualization-guest | delete-vm | Debug virsh netinfo
  ansible.builtin.debug:
    var: virsh_net_facts
    verbosity: 1

- name: ansible-virtualization-guest | delete-vm | extract machine net info
  vars:
    query: "[?hostname == '{{ vm.name.split(\".\").0 }}' ]"
  ansible.builtin.debug:
    msg: "{{ (virsh_net_facts.ansible_facts.ansible_libvirt_networks.default.dhcp_leases | json_query(query)) }}"
  register: currentvm_to_delete_infos

- name: ansible-virtualization-guest | delete-vm | Debug virsh netinfo
  ansible.builtin.debug:
    var: currentvm_to_delete_infos
    verbosity: 1

- name: ansible-virtualization-guest | delete-vm | remove dhcp host configuration
  ansible.builtin.command: "virsh net-update default delete ip-dhcp-host \"<host mac='{{ currentvm_to_delete_infos.msg.0.mac }}' id='{{ currentvm_to_delete_infos.msg.0.clientid }}' name='{{ vm.name }}' ip='{{ currentvm_to_delete_infos.msg.0.ipaddr }}'/>\"  --live"
  changed_when: false
  failed_when: false
  become: true

- name: ansible-virtualization-guest | delete-vm | remove dhcp host configuration
  ansible.posix.firewalld:
    rich_rule: "rule family=ipv4 forward-port port={{ vm.ssh_port_on_host }} log prefix=ssh-to-guest-{{ vm.name }} protocol=tcp to-port=22 to-addr={{ currentvm_to_delete_infos.msg.0.ipaddr }} log prefix=ssh-to-guest-{{ vm.name }} accept"
    zone: public
    permanent: yes
    immediate: yes
    state: disabled
  become: true

- name: ansible-virtualization-guest | delete-vm | stop vm
  community.libvirt.virt:
    name: "{{ vm.name }}"
    state: shutdown
  become: yes

- name: ansible-virtualization-guest | delete-vm | destroy vm
  community.libvirt.virt:
    name: "{{ vm.name }}"
    state: destroyed
  become: yes

- name: ansible-virtualization-guest | delete-vm | remove vm image
  ansible.builtin.file:
    path: "/var/lib/libvirt/images/{{ vm.name }}.img"
    state: absent
  become: yes

- name: ansible-virtualization-guest | delete-vm | persistent facts
  ansible.builtin.template:
    src: configured_vm_facts.j2
    dest: "{{ fact_path | default('/etc/ansible/facts.d') }}/ansible_virtualization_guest.fact"
    owner: root
    group: root
    mode: '0600'
  vars:
    ansible_virtualization_guest_configuredvms: "{{ virtualization_guest_boxes | reject('equalto', vm) | list }}"
  become: true

