---

- name: Delete vm | get the network facts
  community.libvirt.virt_net:
    command: facts
  become: true
  register: virsh_net_facts

- name: Delete vm | Debug virsh netinfo
  ansible.builtin.debug:
    var: virsh_net_facts
    verbosity: 1

- name: Delete vm | stop vm
  community.libvirt.virt:
    name: "{{ virtualmachine.name }}"
    state: shutdown
  failed_when: false
  become: yes

- name: Delete vm | extract machine net info
  vars:
    query: "[?hostname == '{{ virtualmachine.name.split(\".\")[0] | lower }}' ]"
  ansible.builtin.debug:
    msg: "{{ virsh_net_facts.ansible_facts.ansible_libvirt_networks.default.dhcp_leases | json_query(query) }}"
  register: currentvm_to_delete_infos

- name: Delete vm | run vms
  ansible.builtin.include_role:
    name: stackhpc.libvirt-vm
  vars:
    ansible_become: yes
    libvirt_vms:
      - state: absent
        name: "{{ virtualmachine.name }}"

- name: Delete vm | stop vm
  community.libvirt.virt:
    name: "{{ virtualmachine.name }}"
    command: undefine
  failed_when: false
  become: yes

- name: Delete vm | Debug virsh netinfo
  ansible.builtin.debug:
    var: currentvm_to_delete_infos
    verbosity: 1

- name: Delete vm | remove firewalld rich rule for tcp
  ansible.posix.firewalld:
    rich_rule: "rule family=ipv4 forward-port port={{ virtualmachine.ssh_port_on_host }} protocol=tcp to-port=22 to-addr={{ currentvm_to_delete_infos.msg.0.ipaddr }} log prefix=ssh-to-guest-{{ virtualmachine.name }}-tcp"
    zone: public
    permanent: yes
    immediate: yes
    state: disabled
  when: currentvm_to_delete_infos.msg and currentvm_to_delete_infos.msg | length > 0
  become: true

- name: Delete vm | remove firewalld rich rule for udp
  ansible.posix.firewalld:
    rich_rule: "rule family=ipv4 forward-port port={{ virtualmachine.ssh_port_on_host }} protocol=udp to-port=22 to-addr={{ currentvm_to_delete_infos.msg.0.ipaddr }} log prefix=ssh-to-guest-{{ virtualmachine.name }}-udp"
    zone: public
    permanent: yes
    immediate: yes
    state: disabled
  when: currentvm_to_delete_infos.msg and currentvm_to_delete_infos.msg | length > 0
  become: true

- name: Delete vm | remove vm image
  ansible.builtin.file:
    path: "{{ libvirt_volume_default_images_path }}/{{ virtualmachine.name }}.img"
    state: absent
  become: yes

- name: Delete vm | delete VM from facts
  ansible.builtin.replace:
    path: "{{ fact_path | default('/etc/ansible/facts.d') }}/ansible_virtualization_guest.fact"
    regexp: '{{ virtualmachine.name }}(,)?'
    replace: ''
    owner: root
    group: root
    mode: "0644"
  failed_when: false
  become: true

- name: Delete vm | reboot libvirtd # bug in firewalld
  ansible.builtin.service:
    name: libvirtd
    state: restarted
  changed_when: false
  failed_when: false
  become: true
