---

- name: ansible-virtualization-guest | host-ip-forwarding | permanently allow traffic forwarding on host nic
  ansible.posix.sysctl:
    name: net.ipv4.ip_forward
    value: '1'
    sysctl_set: yes
    state: present
    reload: yes

- name: ansible-virtualization-guest | host-ip-forwarding | permanently allow traffic forwarding on host nic
  ansible.posix.sysctl:
    name: net.ipv6.conf.all.forwarding
    value: '1'
    sysctl_set: yes
    state: present
    reload: yes
