---
# tasks file for ansible-virtualization-guest

- name: ansible-virtualization-guest | initialize persistent facts
  include_tasks: persistent-facts.yml

- name: ansible-virtualization-guest | create remote temporary directory
  changed_when: false
  tempfile:
    state: directory
    suffix: isos
  register: isosTempRemoteDirectory

- name: "ansible-virtualization-guest | Extract {{ box.name }}.tar into libvirt images folder"
  include_tasks: unarchive-box.yml
  loop: "{{ virtualization_guest_boxes }}"
  loop_control:
    loop_var: box

- name: ansible-virtualization-guest | run vms
  include_role:
    name: stackhpc.libvirt-vm
  vars:
    ansible_become: yes
    libvirt_vms:
      - state: present
        name: "{{ box.name }}"
        memory_mb: "{{ box.memory_mb }}"
        vcpus: "{{ box.vcpus }}"
        ssh_port_on_host: "{{ box.ssh_port_on_host | int }}" # same as the one in molecule.yml
        ansible_groups: "{{ box.ansible_groups }}"
        volumes:
          - name: "{{ box.name }}.img"
            device: 'disk'
            type: 'file'
            capacity: "{{ box.size | default(ansible_virtualization_guest_min_image_size) }}"
            format: 'qcow2'
            target: "{{ ansible_virtualization_guest_vm_image_target }}"
        interfaces: "{{ box.interfaces }}"
  loop: "{{ virtualization_guest_boxes }}"
  loop_control:
    loop_var: box

- name: Get current user.
  command: whoami
  changed_when: false
  become: false
  register: whoami

- name: ansible-virtualization-guest | debug whoami
  debug:
    var: whoami
    verbosity: 2

- debug:
    msg: "{{ lookup('env', 'USER') }}"
    verbosity: 2

- name: ansible-virtualization-guest | ensure ssh directory is here
  file:
    path: "/home/{{ whoami.stdout }}/.ssh"
    state: directory
    owner: "{{ whoami.stdout }}"
    group: "{{ whoami.stdout }}"
    mode: '0700'

- name: ansible-virtualization-guest | Add libvirt group to current user
  user:
    name: "{{ item.stdout }}"
    groups: libvirt
    append: yes
  become: true
  with_items:
    - "{{ whoami }}"

- name: ansible-virtualization-guest | applies host network forwarding
  include_tasks: host-ip-forwarding.yml

- name: ansible-virtualization-guest | loop over vms
  include_tasks: vm.yml
  loop: "{{ virtualization_guest_boxes }}"
  loop_control:
    loop_var: vm

- name: save persistent facts
  template:
    src: configured_wm_facts.j2
    dest: "{{ fact_path | default('/etc/ansible/facts.d') }}/ansible_virtualization_guest.fact"
    owner: root
    group: root
    mode: '0600'
  become: true

