---
# tasks file for ansible-virtualization-guest
- name: ansible-virtualization-guest | create default tree and variables
  ansible.builtin.include_tasks: directories-and-users.yml

- name: ansible-virtualization-guest | install prerequisite - cronie
  package:
    name: "{{ item }}"
    state: present
  become: true
  with_items:
    - cronie-anacron

- name: ansible-virtualization-guest | delete vms
  ansible.builtin.include_tasks: delete-vm.yml
  loop: "{{ virtualization_guest_boxes | selectattr('recreate_machine', 'defined') | selectattr('recreate_machine', 'equalto', True) }}"
  loop_control:
    loop_var: virtualmachine

- name: ansible-virtualization-guest | initialize persistent facts
  ansible.builtin.include_tasks: persistent-facts.yml

- name: ansible-virtualization-guest | vms to (re)create
  debug:
    msg: "{{ virtualization_guest_boxes | selectattr('recreate_machine', 'defined') | selectattr('recreate_machine', 'equalto', True) | union( virtualization_guest_boxes | rejectattr('name', 'in', ansible_virtualization_guest_facts_configured_vm.msg)) }}"
  register: vmstocreate

- name: ansible-virtualization-guest | prepare vm setup
  ansible.builtin.include_tasks: prepare-vm-setup.yml

- name: ansible-virtualization-guest | loop over vms
  ansible.builtin.include_tasks: vm.yml
  loop: "{{ vmstocreate.msg }}"
  loop_control:
    loop_var: virtualmachine

- name: ansible-virtualization-guest | post creation actions
  ansible.builtin.include_tasks: post-create.yml

- name: ansible-virtualization-guest | save persistent facts
  ansible.builtin.template:
    src: configured_vm_facts.j2
    dest: "{{ fact_path | default('/etc/ansible/facts.d') }}/ansible_virtualization_guest.fact"
    owner: root
    group: root
    mode: '0644'
  vars:
    ansible_virtualization_guest_configuredvms: "{{ virtualization_guest_boxes | selectattr('recreate_machine', 'defined') | selectattr('recreate_machine', 'equalto', False) }}"
  become: true
