---

- virt_net:
    command: info
    name: "{{ nic.network }}"
  register: netinfo
  retries: 40
  delay: 10
  until: netinfo.networks.default.dhcp_leases | length > 0

- name: Debug netinfo
  debug:
    var: netinfo

- name: ansible-virtualization-guest | configure permanent ip
  virt_net:
    name: "{{ nic.network }}"
    command: modify
    xml: "<host mac='{{ hostcheck.mac }}' id='{{ hostcheck.clientid }}' ip='{{ hostcheck.ipaddr }}'/>"
  become: true
  loop: "{{ netinfo.networks.default.dhcp_leases }}" # default here should be the referenced interface
  loop_control:
    loop_var: hostcheck
  when: not netinfo.failed