---

- name: try to wait leases
  block:
  - name: wait for leases to be available
    virt_net:
      command: info
      name: "{{ nic.network }}"
    register: netinfo
    retries: 40
    delay: 10
    until: netinfo.networks.default.dhcp_leases | length > 0
  rescue:
    - name: debug vm log
      command: "cat {{ console_log_path }}"
      register: vmlog
      become: true
      changed_when: false
    - name: display vm log
      debug:
        cmd: "cat {{ console_log_path }}"
    - name: force failure
      command: "/bin/false"
      changed_when: false

- name: Debug netinfo
  debug:
    var: netinfo
    verbosity: 1

- name: ansible-virtualization-guest | configure permanent ip
  virt_net:
    name: "{{ nic.network }}"
    command: modify
    xml: "<host mac='{{ hostcheck.mac }}' id='{{ hostcheck.clientid }}' ip='{{ hostcheck.ipaddr }}'/>"
  become: true
  loop: "{{ netinfo.networks.default.dhcp_leases }}" # default here should be the referenced interface
  loop_control:
    loop_var: hostcheck
  when: not netinfo.failed