---

- name: Collect only facts returned by facter
  ansible.builtin.setup:

- name:  ansible-virtualization-guest | persistent-facts | read all local facts
  ansible.builtin.debug:
    msg: "{{ ansible_local | default ('') }}"
  register: ansible_virtualization_guest_configuredvms_tmp

- name:  ansible-virtualization-guest | persistent-facts | read persisted facts
  ansible.builtin.debug:
    msg: "{{ ansible_local['ansible_virtualization_guest']['general']['configuredvm'] | default ('') }}"
  register: ansible_virtualization_guest_configuredvms_tmp
