---

- name: Prepare-vm-setup | create remote temporary directory
  changed_when: false
  ansible.builtin.tempfile:
    state: directory
    suffix: isos
  register: isos_temp_remote_directory

- name: Prepare-vm-setup | create libvirt group
  ansible.builtin.include_role:
    name: tcharl.ansible_localuser
  vars:
    ansible_become: yes
    local_users_group_list:
      - name: libvirt

# not using ansible_user role here as we append the group
- name: Prepare-vm-setup | Add libvirt group to current user
  ansible.builtin.user:
    name: "{{ item.stdout }}"
    groups: libvirt
    append: yes
  become: true
  with_items:
    - "{{ whoami }}"

- name: Prepare-vm-setup | create libvirt conf folder
  ansible.builtin.file:
    state: directory
    dest: "/etc/libvirt"
    mode: "0700"
    owner: "root"
    group: "root"
  become: true

- name: Prepare-vm-setup | create qemu hooks folder
  ansible.builtin.file:
    state: directory
    dest: "/etc/libvirt/hooks"
    mode: "0755"
  become: true

- name: Prepare-vm-setup | create qemu hook
  ansible.builtin.template:
    src: qemu-hook.j2
    dest: "{{ item }}"
    owner: root
    group: root
    mode: '0755'
  with_items:
    - /etc/libvirt/hooks/qemu
    - /etc/libvirt/hooks/daemon
  notify: ansible-virtualization-guest | refresh libvirtd
  become: true
