---

- name: "ansible-virtualization-guest  | vm | Extract {{ virtualmachine.name }}.tar into libvirt images folder"
  ansible.builtin.include_tasks: unarchive-box.yml

- name: ansible-virtualization-guest | run vms
  ansible.builtin.include_role:
    name: stackhpc.libvirt-vm
  vars:
    ansible_become: yes
    libvirt_vms:
      - state: present
        name: "{{ virtualmachine.name }}"
        memory_mb: "{{ virtualmachine.memory_mb }}"
        vcpus: "{{ virtualmachine.vcpus }}"
        ssh_port_on_host: "{{ virtualmachine.ssh_port_on_host | int }}" # same as the one in molecule.yml
        ansible_groups: "{{ virtualmachine.ansible_groups }}"
        volumes:
          - name: "{{ virtualmachine.name }}.img"
            device: 'disk'
            type: 'file'
            capacity: "{{ virtualmachine.size | default(ansible_virtualization_guest_min_image_size) }}"
            format: 'qcow2'
            target: "{{ ansible_virtualization_guest_vm_image_target }}"
        interfaces: "{{ virtualmachine.interfaces }}"

- name: ansible-virtualization-guest | vm | vm xml
  community.libvirt.virt:
    name: "{{ virtualmachine.name }}"
    command: get_xml
  register: vmxml

- name: ansible-virtualization-guest | vm | Debug vminfo
  ansible.builtin.debug:
    var: vmxml
    verbosity: 1

- name: ansible-virtualization-guest | vm | loop over nics
  ansible.builtin.include_tasks: network.yml
  loop: "{{ virtualmachine.interfaces }}"
  loop_control:
    loop_var: nic

- name: ansible-virtualization-guest | network | reboot libvirtd
  ansible.builtin.service:
    name: libvirtd
    state: restarted
  changed_when: false
  become: true
