---

- name: ansible-virtualization-guest | vm | vm xml
  community.libvirt.virt:
    name: "{{ vm.name }}"
    command: get_xml
  register: vmxml

- name: ansible-virtualization-guest | vm | Debug vminfo
  ansible.builtin.debug:
    var: vmxml
    verbosity: 1

- name: ansible-virtualization-guest | vm | loop over nics
  ansible.builtin.include_tasks: network.yml
  loop: "{{ vm.interfaces }}"
  loop_control:
    loop_var: nic
