---

- name: "Vm | Extract box into libvirt images folder for vm {{ virtualmachine.name }}"
  ansible.builtin.include_tasks: unarchive-box.yml

- name: Vm | run vms
  ansible.builtin.include_role:
    name: stackhpc.libvirt-vm
  vars:
    ansible_become: yes
    libvirt_vms:
      - state: present
        name: "{{ virtualmachine.name }}"
        memory_mb: "{{ virtualmachine.memory_mb }}"
        vcpus: "{{ virtualmachine.vcpus }}"
        ssh_port_on_host: "{{ virtualmachine.ssh_port_on_host | int }}" # same as the one in molecule.yml
        ansible_groups: "{{ virtualmachine.ansible_groups }}"
        volumes:
          - name: "{{ virtualmachine.name }}.img"
            device: 'disk'
            type: 'file'
            capacity: "{{ virtualmachine.size | default(ansible_virtualization_guest_min_image_size) }}"
            format: 'qcow2'
            target: "{{ ansible_virtualization_guest_vm_image_target }}"
        interfaces: "{{ virtualmachine.interfaces }}"

- name: Vm | vm xml
  community.libvirt.virt:
    name: "{{ virtualmachine.name }}"
    command: get_xml
  register: vmxml

- name: Vm | Debug vminfo
  ansible.builtin.debug:
    var: vmxml
    verbosity: 1

- name: Vm | loop over nics
  ansible.builtin.include_tasks: network.yml
  loop: "{{ virtualmachine.interfaces }}"
  loop_control:
    loop_var: nic

- name: Vm | systemd-resolved restarter
  ansible.builtin.template:
    src: 1systemd-resolved-vm.j2
    dest: "/etc/cron.hourly/1systemd-resolved-{{ virtualmachine.name }}"
    owner: root
    group: root
    mode: '0755'
  become: true
