---

- name: ansible-routing | nginx-proxy | install docker
  import_role:
    name: tcharl.ansible_containerization

- name: ansible-routing | nginx-proxy | create nginx directories
  become: true
  with_items:
    - "{{ docker_shared_data_nginx_proxy_path }}"
    - "{{ docker_shared_data_nginx_proxy_certs_path }}"
    - "{{ docker_shared_data_nginx_proxy_vhosts_path }}"
    - "{{ docker_shared_data_nginx_proxy_html_path }}"
    - "{{ docker_shared_data_letsencrypt_path }}"
  file:
    state: directory
    dest: '{{ item }}'
    mode: "0753"

- name: ansible-routing | nginx-proxy | create default index.html
  copy:
    src: index.html
    dest: "{{ docker_shared_data_nginx_proxy_html_path }}"
    owner: root
    group: root
    mode: 0644
  become: true

- name: ansible-routing | nginx-proxy | default domain configuration
  copy:
    src: vhost
    dest: "{{ docker_shared_data_nginx_proxy_vhosts_path }}/default"
    owner: root
    group: root
    mode: '0644'
  become: true

- name: ansible-routing | nginx-proxy | copy virtualHost configuration
  ansible.builtin.template:
    src: vhost.j2
    dest: "{{ docker_shared_data_nginx_proxy_vhosts_path }}/{{ virtual_host.name }}"
    owner: root
    group: root
    mode: '0644'
  become: true

- name: ansible-routing | nginx-proxy | domain location configuration
  ansible.builtin.template:
    src: vhost_location.j2
    dest: "{{ docker_shared_data_nginx_proxy_vhosts_path }}/{{ virtual_host.name }}_location"
    owner: root
    group: root
    mode: '0644'
  become: true

- name: ansible-routing | nginx-proxy | start proxy
  docker_container:
    name: nginx-proxy
    image: jwilder/nginx-proxy
    restart_policy: "always"
    published_ports: "{{ virtual_host.ports_binding }}"
    volumes:
      - "/var/run/docker.sock:/tmp/docker.sock:ro"
      - "{{ docker_shared_data_nginx_proxy_certs_path }}:/etc/nginx/certs"
      - "{{ docker_shared_data_nginx_proxy_vhosts_path }}:/etc/nginx/vhost.d"
      - "{{ docker_shared_data_nginx_proxy_html_path }}:/usr/share/nginx/html"
    state: started
  become: true

- name: ansible-routing | nginx-proxy | letsencrypt-companion
  docker_container:
    name: letsencrypt-companion
    image: jrcs/letsencrypt-nginx-proxy-companion
    restart_policy: "always"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "{{ docker_shared_data_letsencrypt_path }}:/etc/acme.sh"
    volumes_from:
      - nginx-proxy
    env:
      DEFAULT_EMAIL: "{{ letsencrypt_default_email }}"
    state: started
  when: virtual_host.gen_certs | default(false)
  become: true
