---

- name: ansible-routing | services-ports | enable services
  become: "{{ firewalld_become }}"
  ansible.posix.firewalld:
    zone: "{{ zone.name | default('public') }}"
    permanent: true
    immediate: true
    service: "{{ enabled_service.service }}"
    state: enabled
  loop: "{{ zone.enabled_services | default([]) }}"
  loop_control:
    loop_var: enabled_service

- name: ansible-routing | services-ports | open port
  ansible.posix.firewalld:
    port: "{{ enabled_port.port }}/{{ enabled_port.protocol | default('tcp') }}"
    zone: "{{ zone.name | default('public') }}"
    permanent: true
    immediate: true
    state: enabled
  become: "{{ firewalld_become }}"
  loop: "{{ zone.enabled_ports | default([]) }}"
  loop_control:
    loop_var: enabled_port
