---

- name: ansible-nameserver | bind_config | gather all ips of the bind client group
  setup:
  register: hostfacts

- name: ansible-virtualization-guest | network | Debug fullnetinfo
  debug:
    var: hostfacts
    verbosity: 3
  when: not zone.nics is defined

- name: ansible-routing | zone | create zones - without permanent
  become: "{{ firewalld_become }}"
  ansible.posix.firewalld:
    zone: "{{ zone.name | default('public') }}"
    immediate: true
    state: enabled

- name: ansible-routing | zone | create zones
  become: "{{ firewalld_become }}"
  ansible.posix.firewalld:
    zone: "{{ zone.name | default('public') }}"
    permanent: true
    immediate: true
    state: enabled

- name: ansible-routing | zone | affect nics
  become: "{{ firewalld_become }}"
  ansible.posix.firewalld:
    zone: "{{ zone.name | default('public') }}"
    permanent: true
    immediate: true
    interface: "{{ unaffectednic }}"
    state: enabled
  loop: "{{ zone.nics | default(hostfacts.ansible_facts.ansible_interfaces) }}"
  loop_control:
    loop_var: unaffectednic
  when: zone.nics is defined

- name: ansible-routing | zone | configure firewalld masquerade
  become: "{{ firewalld_become }}"
  ansible.posix.firewalld:
    masquerade: true|bool
    state: enabled
    permanent: true
    zone: "{{ zone.name | default('public') }}"
  notify: ansible-routing | handler | reload-firewall

- name: ansible-routing | zone | configure forwarding
  include: port-forwarding.yml
  loop: "{{ zone.port_forward_rules | default([]) }}"
  loop_control:
    label: "{{ forward_rule.port_forward_rule }}"
    loop_var: forward_rule
  notify: ansible-routing | handler | reload-firewall

- name: ansible-routing | zone | configure ports and services
  include: services-ports.yml
