---

- name: ansible-virtualization-guest | handler | reboot libvirtd # bug in firewalld
  ansible.builtin.service:
    name: libvirtd
    state: restarted
  changed_when: false
  listen: ansible-virtualization-guest | refresh libvirtd
  become: true
