---
# handlers file for ansible-routing

- name: ansible-routing | handler | reload-firewall
  service:
    name: firewalld
    state: reloaded
  become: yes
  listen: ansible-routing | handler | reload-firewall

- name: ansible-routing | handler | restart-firewall
  service:
    name: firewalld
    state: restarted
  become: yes
  listen: ansible-routing | restart | restart-firewall
