---
roles:
  # Install a role from Ansible Galaxy.
  - name: robertdebock.users
    source: https://galaxy.ansible.com
    path: ../community
  - name: robertdebock.bootstrap
    source: https://galaxy.ansible.com
    path: ../community
  - name: robertdebock.core_dependencies
    source: https://galaxy.ansible.com
    path: ../community
  - name: tcharl.ansible_routing
    source: https://galaxy.ansible.com
    path: ../community
  - name: tcharl.ansible_securehost
    source: https://galaxy.ansible.com
    path: ../community
  - name: tcharl.hostname
    source: https://galaxy.ansible.com
    path: ../community
  - name: robertdebock.fail2ban
    source: https://galaxy.ansible.com
    path: ../community
  - name: robertdebock.epel
    source: https://galaxy.ansible.com
    path: ../community
