---
- name: Converge
  hosts: all
  vars:
    manage_lvm: true
    lvm_groups:
      - vgname: non-persistent
        disks:
          - /dev/vdb
        create: true
        lvnames: []
    virtualization_guest_boxes:
      - name: fedoraGuestVM
        url: https://app.vagrantup.com/fedora/boxes/38-cloud-base/versions/38.20230413.1/providers/libvirt.box
        memory_mb: 2048
        vcpus: 2
        ssh_port_on_host: 6752 # same as the one in molecule.yml
        recreate_machine: False
        ansible_groups:
          - directory
          - openid
        interfaces:
          - network: default
    users_group_list2:
      - name: libvirt
    systemusers_user_list:
      - name: libvirt
        group: libvirt
        groups: wheel
    libvirt_host_pools:
      - name: libvirt_vg
        type: lvm2
        source: non-persistent
    libvirt_host_networks:
      - name: default
        mode: nat
        bridge: virbr0
        ip: 192.168.121.1
        netmask: 255.255.255.0
        dhcp_start: 192.168.121.100
        dhcp_end: 192.168.121.200
  roles:
    - role: tcahrl.ansible_virtualization_guest
  tasks:
    - name: ansible-virtualization-guest | handler | execute hook # firewalld overriding vm NAT
      ansible.builtin.service:
        name: libvirtd
        state: restarted
      become: true
