---
dependency:
  name: galaxy
  options:
    requirements-file: requirements-collections.yml
    collections-path: ${MOLECULE_PROJECT_DIRECTORY}/../community-collections
    role-file: requirements.yml
    roles-path: ${MOLECULE_PROJECT_DIRECTORY}/../community
driver:
  name: vagrant
  provider:
    name: libvirt
lint: |
  set -e
  yamllint .
  flake8
  ANSIBLE_ROLES_PATH=${MOLECULE_PROJECT_DIRECTORY}/../community ANSIBLE_COLLECTIONS_PATH=${MOLECULE_PROJECT_DIRECTORY}/../community-collections ansible-lint
platforms:
  - name: Fedora-Molecule-virtualization-Guest
    box: fedora/34-cloud-base
    provider_options:
      driver: '"kvm"'
      cpus: 4
      memory: 4096
    instance_raw_config_args:
      - "vm.network :forwarded_port, guest: 6752, host: 6752, protocol: 'tcp'"
    provider_raw_config_args:
      - "storage :file, :size => '1G', :device => 'vdb'"
provisioner:
  name: ansible
  config_options:
    defaults:
      forks: 20
    ssh_connection:
      pipelining: true
      ssh_args: -o ControlMaster=auto -o ControlPersist=600s
  env:
    ANSIBLE_ROLES_PATH: ${ANSIBLE_ROLES_PATH}:${MOLECULE_PROJECT_DIRECTORY}/../community:${MOLECULE_PROJECT_DIRECTORY}/..
    ANSIBLE_COLLECTIONS_PATH: ${ANSIBLE_COLLECTIONS_PATH}:${MOLECULE_PROJECT_DIRECTORY}/../community-collections
verifier:
  name: testinfra
  env:
    PYTHONWARNINGS: "ignore:.*U.*mode is deprecated:DeprecationWarning"
  options:
    v: 1
scenario:
  name: kvm
