---
# TODO This phase fails once

- name: Report machine
  hosts:
    - all
  tasks:
    - name: "Cat"
      ansible.builtin.command:
        cmd: df -h
      changed_when: false
      register: df_output
      become: true
    - ansible.builtin.debug:
        msg: "{{ df_output.stdout }}"
