---
dependency:
  name: galaxy
  options:
    requirements-file: requirements-collections.yml
    collections-path: ../community-collections
    role-file: requirements.yml
    roles-path: ../community
driver:
  name: docker
lint: yamllint . && flake8 && ansible-lint --exclude=meta
platforms:
  - name: ansible-users-vm
    image: robertdebock/fedora:32
    command: /sbin/init
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    privileged: yes
    pre_build_image: yes

provisioner:
  name: ansible
  env:
    ANSIBLE_ROLES_PATH: ${ANSIBLE_ROLES_PATH}:../../../community
    ANSIBLE_COLLECTIONS_PATH: ${ANSIBLE_COLLECTIONS_PATH}:../community-collections
verifier:
  name: testinfra
  env:
    PYTHONWARNINGS: "ignore:.*U.*mode is deprecated:DeprecationWarning"
  options:
    v: 1
