---
roles:
  - name: tcharl.ansible_manage_lvm
    source: https://galaxy.ansible.com
    path: ../community

  - name: tcharl.ansible_users
    source: https://galaxy.ansible.com
    path: ../community

  - name: robertdebock.users
    source: https://galaxy.ansible.com
    path: ../community

  - name: robertdebock.bootstrap
    source: https://galaxy.ansible.com
    path: ../community

  - name: robertdebock.core_dependencies
    source: https://galaxy.ansible.com
    path: ../community

  - name: tcharl.ansible_role_libvirt_host
    source: https://galaxy.ansible.com
    path: ../community
